security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]

        fos_facebook_provider:
                id: fos_facebook.user.login
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/.*
            fos_facebook:
                 app_url: "http://apps.facebook.com/codelabent/"
                 server_url: "http://codelab24/app_dev.php/"
                 login_path:  /login
                 check_path: /facebook/login_check
                 provider: fos_facebook_provider
                 default_target_path: /

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:
                #path: /user/logout
            anonymous: ~
            remember_me:
                  key:      mySuperDuperKey
                  lifetime: 4147200
                  path:     /
                  domain:   ~

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/song/, role: ROLE_USER }

    acl:
        connection: default
