<?php

namespace Application\Main\CartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductByCode($id, $approved = true)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.code = :code')
            ->setParameter('code', $id);

        if (false === is_null($approved))
            $qb->andWhere('p.isActive = :approved')
                ->setParameter('approved', $approved);

        return $qb->getQuery()
            ->getSingleResult();
    }
}
