<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *@ORM\Entity
  * @ORM\Table()
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }



        public function serialize()
            {
                return serialize(array($this->facebookUid, parent::serialize()));
            }

            public function unserialize($data)
            {
                list($this->facebookUid, $parentData) = unserialize($data);
                parent::unserialize($parentData);
            }

            /**
             * Get the full name of the user (first + last name)
             * @return string
             */
            public function getFullName()
            {
                return $this->getFirstname() . ' ' . $this->getLastname();
            }



            /**
             * @param Array
             */
            public function setFBData($fbdata)
            {
                if (isset($fbdata['id'])) {
                    $this->setFacebookUid($fbdata['id']);
                    $this->addRole('ROLE_FACEBOOK');
                }
                if (isset($fbdata['first_name'])) {
                    $this->setFirstname($fbdata['first_name']);
                }
                if (isset($fbdata['last_name'])) {
                    $this->setLastname($fbdata['last_name']);
                }
                if (isset($fbdata['email'])) {
                    $this->setEmail($fbdata['email']);
                }
            }




}