<?php

namespace Application\Main\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getAlbumsByArtist($id, $approved = true)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->leftJoin('a.artists', "artist")
            ->select('a')
            ->where('artist.id = :id')
            ->setParameter('id', $id);

//        if (false === is_null($approved))
//            $qb->andWhere('a.isActive = :approved')
//                ->setParameter('approved', $approved);

        return $qb->getQuery()
            ->getResult();


    }

}
