<?php

namespace Application\Main\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends EntityRepository
{
    public function getSongsByAlbum($id, $approved = true)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.albums', "album")
            ->select('s')
            ->where('album.id = :id')
            ->setParameter('id', $id);

//        if (false === is_null($approved))
//            $qb->andWhere('a.isActive = :approved')
//                ->setParameter('approved', $approved);

        return $qb->getQuery()
            ->getResult();


    }
}
